sx_order/urls.py
from django.conf.urls import url

from sx_order import views

urlpatterns = [
    # 提交订单
    url(r'^place_order/', views.place_order, name='place_order'),
    # 用户中心 - 用户信息页
    url(r'^user_center_info/', views.user_center_info, name='user_center_info'),
    # 用户中心 - 用户订单页
    url(r'^user_center_order/', views.user_center_order, name='user_center_order'),
    # 用户中心 - 用户收货地址页
    url(r'^user_center_site/', views.user_center_site, name='user_center_site'),
]

sx_shopping/urls.py
from django.conf.urls import url

from sx_shopping import views

urlpatterns = [
    # 商品详情
    url(r'^detail/', views.detail, name='detail'),
    # 增加商品数量
    url(r'^addgoods/', views.add_goods, name='addgoods'),
    # 减少商品数量
    url(r'^subgoods/', views.sub_goods, name='subgoods'),
    # 刷新增添与减少商品数量
    url(r'^goodsnum/', views.goods_num, name='goodsnum'),
    # 加入购物车
    url(r'^addcart/', views.add_cart, name='addcart'),
    # 立即购买
    url(r'^buycart/', views.buy_cart, name='buycart'),
    # 计算商品总价
    url(r'^tatalprice/', views.tatal_price, name='tatalprice'),
    # 删除购物车商品
    url(r'^delgoodscart/', views.del_goods_cart, name='delgoodscart'),

]

sx_store/urls.py
from django.conf.urls import url

from sx_store import views

urlpatterns = [
    # 商城首页
    url(r'^index/', views.index, name='index'),
    # 商城商品列表页
    url(r'^list/', views.list, name='list'),
]

sx_user/urls.py
from django.conf.urls import url

from sx_user import views

urlpatterns = [
    # 注册
    url(r'^register/', views.register, name='register'),
    # 登陆
    url(r'^login/', views.login, name='login'),
    # 退出
    url(r'^logout/', views.logout, name='logout'),
]

ttsx/urls.py
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import static

from ttsx import settings

urlpatterns = [
    # 后台管理路由
    url(r'^admin/', include('ttsxAdmin.urls', namespace='admin')),
    # 用户中心路由
    url(r'^user/', include('sx_user.urls', namespace='user')),
    # 商城展示路由
    url(r'^store/', include('sx_store.urls', namespace='store')),
    # 购物过程路由
    url(r'^shopping/', include('sx_shopping.urls', namespace='shopping')),
    # 订单路由
    url(r'^order/', include('sx_order.urls', namespace='order')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
		{% block title %}{% endblock %}
	</title>
	<link rel="stylesheet" type="text/css" href="{% static 'ttsx/css/reset.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'ttsx/css/main.css' %}"/>
	<script type="text/javascript" src="{% static 'ttsx/js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'ttsx/js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'ttsx/js/slide.js' %}"></script>
    {% block extCSS %}{% endblock %}

</head>

<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					{% if user.id %}
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
					{% else %}
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
					{% endif %}
				</div>

				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'order:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'shopping:buycart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:user_center_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
		<div class="search_bar clearfix">
		<a href="{% url 'store:index' %}" class="logo fl"><img src="{% static 'ttsx/images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'shopping:buycart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
	{% block content %}{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

{% block extJS %}{% endblock %}

</body>
</html>

templates/base_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
		{% block title %}{% endblock %}
	</title>
	<link rel="stylesheet" type="text/css" href="{% static 'ttsx/css/reset.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'ttsx/css/main.css' %}"/>
    {% block extCSS %}{% endblock %}
</head>

<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					{% if user.id %}
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
					{% else %}
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
					{% endif %}
				</div>

				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'order:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'shopping:buycart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:user_center_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'store:index' %}" class="logo fl"><img src="{% static 'ttsx/images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block abr %}{% endblock %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
	{% block content %}{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2017 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

	<script type="text/javascript" src="{% static 'ttsx/js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'ttsx/common/functions.js' %}"></script>
	{% block extJS %}{% endblock %}

</body>
</html>

templates/cart.html
{% extends 'base_order.html' %}

{% load static %}
{% block title %}天天生鲜-用户中心{% endblock %}
{% block extCSS %}{% endblock %}

{% block abr %}购物车{% endblock %}
{% block content %}
	<div class="total_count">全部商品<em id="all_num1"></em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

{% csrf_token %}
{% for cart in carts %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="/media/{{ cart.goods.g_img }}"></li>
		<li class="col03">{{ cart.goods.g_name }}<br><em>{{ cart.goods.g_price }}元/{{ cart.goods.g_unit }}</em></li>
		<li class="col04">{{ cart.goods.g_unit }}</li>
		<li class="col05">{{ cart.goods.g_price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" onclick="addgoods({{ cart.goods.id }})" class="add fl">+</a>
				<input type="text" class="num_show_{{ cart.goods.id }} fl" value="1">
				<a href="javascript:;" onclick="subgoods({{ cart.goods.id }})" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07"><em id="price{{ cart.goods.id }}" >{{ goods.g_price }}</em> <em>元</em></li>

		<li class="col08"><a href="{% url 'shopping:delgoodscart' %}?cart_id={{ cart.id }}">删除</a></li>
	</ul>
{% endfor %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em id="tatal_price"></em><br>共计<b id="all_num"></b>件商品</li>
		<li class="col04"><a href="{% url 'order:place_order' %}">去结算</a></li>
	</ul>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block title %}天天生鲜-首页{% endblock %}
{% block extCSS %}{% endblock %}

{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="#">首页</a></li>
				<li class="interval">|</li>
				<li><a href="#">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="#">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{% static 'ttsx/images/slide.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'ttsx/images/slide02.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'ttsx/images/slide03.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'ttsx/images/slide04.jpg' %}" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'ttsx/images/adv01.jpg' %}"></a>
			<a href="#"><img src="{% static 'ttsx/images/adv02.jpg' %}"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">新鲜水果</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for good1 in fresh_fruit %}
				<a href="#">{{ good1.g_name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'store:list' %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>


		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'ttsx/images/banner01.jpg' %}"></div>
			<ul onclick="subgoods({{ goods.id }})" class="goods_list fl">
				{% for good1 in fresh_fruit %}
				<li>
					<h4><a href="{% url 'shopping:detail' %}?g_id={{ good1.id }}">{{ good1.g_name }}</a></h4>
					<a href="{% url 'shopping:detail' %}?g_id={{ good1.id }}"><img src="/media/{{ good1.g_img }}"></a>
					<div class="prize">¥ {{ good1.g_price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>

	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">海鲜水产</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for good2 in seafood_aquaculture %}
				<a href="#">{{ good2.g_name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'ttsx/images/banner02.jpg' %}"></div>
			<ul class="goods_list fl">
				{% for good2 in seafood_aquaculture %}
				<li>
					<h4><a href="#">{{ good2.g_name }}</a></h4>
					<a href="#"><img src="/media/{{ good2.g_img }}"></a>
					<div class="prize">¥ {{ good2.g_price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">猪牛羊肉</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for good3 in red_meat %}
				<a href="#">{{ good3.g_name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'ttsx/images/banner03.jpg' %}"></div>
			<ul class="goods_list fl">
				{% for good3 in red_meat %}
				<li>
					<h4><a href="#">{{ good3.g_name }}</a></h4>
					<a href="#"><img src="/media/{{ good3.g_img }}"></a>
					<div class="prize">¥ {{ good3.g_price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">禽类蛋品</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for good4 in poultry_egg %}
				<a href="#">{{ good4.g_name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'ttsx/images/banner04.jpg' %}"></div>
			<ul class="goods_list fl">
				{% for good4 in poultry_egg %}
				<li>
					<h4><a href="#">{{ good4.g_name }}</a></h4>
					<a href="#"><img src="/media/{{ good4.g_img }}"></a>
					<div class="prize">¥ {{ good4.g_price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">新鲜蔬菜</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for good5 in green_goods %}
				<a href="#">{{ good5.g_name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'ttsx/images/banner05.jpg' %}"></div>
			<ul class="goods_list fl">
				{% for good5 in green_goods %}
				<li>
					<h4><a href="#">{{ good5.g_name }}</a></h4>
					<a href="#"><img src="/media/{{ good5.g_img }}"></a>
					<div class="prize">¥ {{ good5.g_price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">速冻食品</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for good6 in quick_frozen %}
				<a href="#">{{ good6.g_name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'ttsx/images/banner06.jpg' %}"></div>
			<ul class="goods_list fl">
				{% for good6 in quick_frozen %}
				<li>
					<h4><a href="#">{{ good6.g_name }}</a></h4>
					<a href="#"><img src="/media/{{ good6.g_img }}"></a>
					<div class="prize">¥ {{ good6.g_price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
{% endblock %}

{% block extJS %}
	<script type="text/javascript" src="{% static 'ttsx/js/slideshow.js' %}"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

templates/list.html
{% extends 'base.html' %}

{% load static %}
{% block title %}天天生鲜-商品列表{% endblock %}
{% block extCSS %}{% endblock %}

{% block content %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					{% for k in kinds %}
					<li><a href="#" class="fruit">{{ k.kind }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for tj in tj_goods %}
					<li>
						<a href="#"><img src="/media/{{ tj.g_img }}"></a>
						<h4><a href="#">{{ tj.g_name }}</a></h4>
						<div class="prize">￥{{ tj.g_price }}</div>
					</li>
					{% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for good in goods %}
				<li>
					<a href="{% url 'shopping:detail' %}?g_id={{ good.id }}"><img src="/media/{{ good.g_img }}"></a>
					<h4><a href="detail.html">{{ good.g_name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ good.g_price }}</span>
						<span class="unit">{{ good.g_price }}/{{ good.g_unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}
			</ul>

			<div class="pagenation">
				<a href="#"><上一页</a>
				<a href="#" class="active">1</a>
				<a href="#">2</a>
				<a href="#">3</a>
				<a href="#">4</a>
				<a href="#">5</a>
				<a href="#">下一页></a>
			</div>
		</div>
	</div>
{% endblock %}

templates/user_center_info.html
{% extends 'base_order.html' %}

{% load static %}
{% block title %}天天生鲜-用户中心{% endblock %}
{% block extCSS %}{% endblock %}

{% block abr %}用户中心{% endblock %}
{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'order:user_center_info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'order:user_center_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'order:user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
		<div class="info_con clearfix">
		<h3 class="common_title2">基本信息</h3>
				<ul class="user_info_list">
					<li><span>用户名：</span>{{ user.username }}</li>
					<li><span>联系方式：</span>{{ user.phone }}</li>
					<li><span>联系地址：</span>{{ user.direction }}</li>
				</ul>
		</div>
				
		<h3 class="common_title2">最近浏览</h3>
		<div class="has_view_list">
			<ul class="goods_type_list clearfix">

				<li>
					<a href="detail.html"><img src="{% static 'ttsx/images/goods/goods003.jpg' %}"></a>
					<h4><a href="detail.html">大兴大棚草莓</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

			</ul>
		</div>
		</div>
	</div>
{% endblock %}

templates/user_center_order.html
{% extends 'base_order.html' %}

{% load static %}
{% block title %}天天生鲜-用户中心{% endblock %}
{% block extCSS %}{% endblock %}

{% block abr %}用户中心{% endblock %}
{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'order:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'order:user_center_order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'order:user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">未支付</li>		
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{% static 'ttsx/images/goods02.jpg' %}"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="{% url 'order:place_order' %}" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">已支付</li>			
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{% static 'ttsx/images/goods02.jpg' %}"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>
					</tbody>
				</table>

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock %}

templates/user_center_site.html
{% extends 'base_order.html' %}

{% load static %}
{% block title %}天天生鲜-用户中心{% endblock %}
{% block extCSS %}{% endblock %}

{% block abr %}用户中心{% endblock %}
{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'order:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'order:user_center_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'order:user_center_site' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user_info.direction }} （{{ user_info.recipients }} 收）
							{{ user_info.phone }} 邮编:{{ user_info.addressee_p }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{msg}}</h3>
				<div class="site_con">
					<form method="post" action="">
						{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="recipients">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="direction"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="addressee_p">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>
						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock %}